name: nostr_event_scheduler
description: Local-first Dart package for scheduling Nostr events via Scheduler DVMs.
version: 0.5.4
repository: https://github.com/nogringo/nostr-event-scheduler
homepage: https://github.com/nogringo/nostr-event-scheduler

topics:
  - nostr
  - scheduler
  - dvm
  - local-first
  - offline-first

environment:
  sdk: ^3.12.0

dependencies:
  ndk: ^0.10.0-dev.6
  sembast: ^3.8.9
  broadcast_queue_shim_for_ndk: ^0.6.0
  sync_engine_shim_for_ndk: ^0.7.1

dev_dependencies:
  bip340: ^0.3.1
  lints: ^6.1.0
  nostr_scheduler_dvm: ^0.4.0
  test: ^1.32.0
