import 'package:ndk/entities.dart' show Nip01Event;

import 'job_status.dart';
import 'scheduled_job_request.dart';

/// Represents a single scheduled event managed by the scheduler.
///
/// A job can be sent redundantly to several Scheduler DVMs. Every DVM
/// receives its own kind:5905 request carrying the same `job_id` and payload,
/// tracked as one [ScheduledJobRequest] in [requests]. All kind:5905 requests
/// sharing a `job_id` schedule the same event at the same time.
class ScheduledJob {
  /// 64-char hex identifier generated by the client, shared by every
  /// kind:5905 request of this job.
  final String jobId;

  /// Unix timestamp when a DVM should publish the event.
  final int scheduleAt;

  /// The original signed event that a DVM should publish.
  final Nip01Event targetEvent;

  /// Relay URLs where a DVM should publish the event.
  final List<String> targetRelays;

  /// One request per Scheduler DVM this job was sent to.
  final List<ScheduledJobRequest> requests;

  /// Unix timestamp when the job was first created locally.
  final int createdAt;

  /// Unix timestamp of the last local update.
  int updatedAt;

  ScheduledJob({
    required this.jobId,
    required this.scheduleAt,
    required this.targetEvent,
    required this.targetRelays,
    required this.requests,
    required this.createdAt,
    required this.updatedAt,
  });

  /// Aggregated lifecycle status across [requests].
  ///
  /// One publication is enough, so the most advanced request wins. See
  /// [JobStatus.aggregate].
  JobStatus get status =>
      JobStatus.aggregate(requests.map((r) => r.status)) ?? JobStatus.pending;

  /// Message of the request that determines [status].
  String? get lastMessage {
    final aggregated = status;
    for (final request in requests) {
      if (request.status == aggregated) return request.lastMessage;
    }
    return null;
  }

  /// Public keys of all Scheduler DVMs this job was sent to.
  List<String> get dvmPubkeys => requests.map((r) => r.dvmPubkey).toList();

  /// IDs of all kind:5905 request events of this job.
  List<String> get requestEventIds =>
      requests.map((r) => r.requestEventId).toList();

  /// The request targeting [dvmPubkey], or null.
  ScheduledJobRequest? requestForDvm(String dvmPubkey) {
    return requests.where((r) => r.dvmPubkey == dvmPubkey).firstOrNull;
  }

  /// The request whose kind:5905 event ID is [requestEventId], or null.
  ScheduledJobRequest? requestForEventId(String requestEventId) {
    return requests
        .where((r) => r.requestEventId == requestEventId)
        .firstOrNull;
  }

  Map<String, dynamic> toJson() {
    return {
      'jobId': jobId,
      'scheduleAt': scheduleAt,
      'targetEvent': {
        'id': targetEvent.id,
        'pubkey': targetEvent.pubKey,
        'created_at': targetEvent.createdAt,
        'kind': targetEvent.kind,
        'tags': targetEvent.tags,
        'content': targetEvent.content,
        'sig': targetEvent.sig,
      },
      'targetRelays': targetRelays,
      'requests': requests.map((r) => r.toJson()).toList(),
      'createdAt': createdAt,
      'updatedAt': updatedAt,
    };
  }

  factory ScheduledJob.fromJson(Map<String, dynamic> json) {
    final eventMap = json['targetEvent'] as Map<String, dynamic>;
    final requestsJson = json['requests'] as List<dynamic>?;
    final requests = requestsJson != null
        ? requestsJson
              .map(
                (r) => ScheduledJobRequest.fromJson(r as Map<String, dynamic>),
              )
              .toList()
        // Single-DVM shape from schema v2, readable until the rebuild runs.
        : [
            ScheduledJobRequest(
              dvmPubkey: json['dvmPubkey'] as String,
              requestEventId: json['requestEventId'] as String,
              status: JobStatus.values.byName(json['status'] as String),
              lastMessage: json['lastMessage'] as String?,
              updatedAt: json['updatedAt'] as int,
            ),
          ];

    return ScheduledJob(
      jobId: json['jobId'] as String,
      scheduleAt: json['scheduleAt'] as int,
      targetEvent: Nip01Event(
        id: eventMap['id'] as String,
        pubKey: eventMap['pubkey'] as String,
        createdAt: eventMap['created_at'] as int,
        kind: eventMap['kind'] as int,
        tags: (eventMap['tags'] as List<dynamic>)
            .map((t) => (t as List<dynamic>).map((e) => e as String).toList())
            .toList(),
        content: eventMap['content'] as String,
        sig: eventMap['sig'] as String,
      ),
      targetRelays: (json['targetRelays'] as List<dynamic>)
          .map((e) => e as String)
          .toList(),
      requests: requests,
      createdAt: json['createdAt'] as int,
      updatedAt: json['updatedAt'] as int,
    );
  }
}
