import 'package:ndk/entities.dart' show Nip01Event;

import 'job_status.dart';

/// Represents a single scheduled event managed by the scheduler.
class ScheduledJob {
  /// 64-char hex identifier generated by the client.
  final String jobId;

  /// ID of the kind:5905 request event that was broadcast.
  final String requestEventId;

  /// Public key of the target Scheduler DVM.
  final String dvmPubkey;

  /// Unix timestamp when the DVM should publish the event.
  final int scheduleAt;

  /// The original signed event that the DVM should publish.
  final Nip01Event targetEvent;

  /// Relay URLs where the DVM should publish the event.
  final List<String> targetRelays;

  /// Current lifecycle status of the job.
  JobStatus status;

  /// Optional human-readable message from the DVM.
  String? lastMessage;

  /// Unix timestamp when the job was first created locally.
  final int createdAt;

  /// Unix timestamp of the last local update.
  int updatedAt;

  ScheduledJob({
    required this.jobId,
    required this.requestEventId,
    required this.dvmPubkey,
    required this.scheduleAt,
    required this.targetEvent,
    required this.targetRelays,
    this.status = JobStatus.pending,
    this.lastMessage,
    required this.createdAt,
    required this.updatedAt,
  });

  Map<String, dynamic> toJson() {
    return {
      'jobId': jobId,
      'requestEventId': requestEventId,
      'dvmPubkey': dvmPubkey,
      'scheduleAt': scheduleAt,
      'targetEvent': {
        'id': targetEvent.id,
        'pubkey': targetEvent.pubKey,
        'created_at': targetEvent.createdAt,
        'kind': targetEvent.kind,
        'tags': targetEvent.tags,
        'content': targetEvent.content,
        'sig': targetEvent.sig,
      },
      'targetRelays': targetRelays,
      'status': status.name,
      'lastMessage': lastMessage,
      'createdAt': createdAt,
      'updatedAt': updatedAt,
    };
  }

  factory ScheduledJob.fromJson(Map<String, dynamic> json) {
    final eventMap = json['targetEvent'] as Map<String, dynamic>;
    return ScheduledJob(
      jobId: json['jobId'] as String,
      requestEventId: json['requestEventId'] as String,
      dvmPubkey: json['dvmPubkey'] as String,
      scheduleAt: json['scheduleAt'] as int,
      targetEvent: Nip01Event(
        id: eventMap['id'] as String,
        pubKey: eventMap['pubkey'] as String,
        createdAt: eventMap['created_at'] as int,
        kind: eventMap['kind'] as int,
        tags: (eventMap['tags'] as List<dynamic>)
            .map((t) => (t as List<dynamic>).map((e) => e as String).toList())
            .toList(),
        content: eventMap['content'] as String,
        sig: eventMap['sig'] as String,
      ),
      targetRelays: (json['targetRelays'] as List<dynamic>)
          .map((e) => e as String)
          .toList(),
      status: JobStatus.values.byName(json['status'] as String),
      lastMessage: json['lastMessage'] as String?,
      createdAt: json['createdAt'] as int,
      updatedAt: json['updatedAt'] as int,
    );
  }

  ScheduledJob copyWith({
    JobStatus? status,
    String? lastMessage,
    int? updatedAt,
  }) {
    return ScheduledJob(
      jobId: jobId,
      requestEventId: requestEventId,
      dvmPubkey: dvmPubkey,
      scheduleAt: scheduleAt,
      targetEvent: targetEvent,
      targetRelays: targetRelays,
      status: status ?? this.status,
      lastMessage: lastMessage ?? this.lastMessage,
      createdAt: createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
    );
  }
}
